import { useCallback, useEffect, useMemo, useState } from "react";
import Modal from "../components/Modal";
import PageHeader from "../components/PageHeader";
import StatePanel from "../components/StatePanel";
import StatusBadge from "../components/StatusBadge";
import { getPatients } from "../services/patientService";
import { getDoctors } from "../services/doctorService";
import { createAppointment, getAppointments } from "../services/appointmentService";

const emptyAppointment = { patientId: "", doctorId: "", appointmentDate: "", appointmentTime: "", reason: "", notes: "", status: "SCHEDULED" };
const today = new Date().toISOString().slice(0, 10);

function Appointments() {
	const [appointments, setAppointments] = useState([]); const [patients, setPatients] = useState([]); const [doctors, setDoctors] = useState([]); const [searchTerm, setSearchTerm] = useState(""); const [doctorFilter, setDoctorFilter] = useState("All doctors"); const [statusFilter, setStatusFilter] = useState("All status");
	const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [isFormOpen, setIsFormOpen] = useState(false); const [formData, setFormData] = useState(emptyAppointment); const [formError, setFormError] = useState(""); const [saving, setSaving] = useState(false); const [successMessage, setSuccessMessage] = useState("");
	const loadData = useCallback(async () => { setLoading(true); setError(""); try { const [appointmentData, patientData, doctorData] = await Promise.all([getAppointments(), getPatients(), getDoctors()]); setAppointments(Array.isArray(appointmentData) ? appointmentData : []); setPatients(Array.isArray(patientData) ? patientData : []); setDoctors(Array.isArray(doctorData) ? doctorData : []); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } }, []);
	useEffect(() => { const initialLoad = window.setTimeout(loadData, 0); return () => window.clearTimeout(initialLoad); }, [loadData]);
	const visibleAppointments = useMemo(() => appointments.filter((appointment) => { const query = searchTerm.trim().toLowerCase(); const matchesSearch = !query || [appointment.appointmentNumber, appointment.patientName, appointment.doctorName, appointment.reason].filter(Boolean).some((value) => value.toLowerCase().includes(query)); return matchesSearch && (doctorFilter === "All doctors" || String(appointment.doctorId) === doctorFilter) && (statusFilter === "All status" || appointment.status === statusFilter); }), [appointments, searchTerm, doctorFilter, statusFilter]);
	const handleChange = ({ target: { name, value } }) => setFormData((current) => ({ ...current, [name]: value }));
	const closeForm = () => { if (!saving) { setIsFormOpen(false); setFormData(emptyAppointment); setFormError(""); } };
	const submit = async (event) => { event.preventDefault(); setFormError(""); setSaving(true); const payload = { ...formData, patientId: Number(formData.patientId), doctorId: Number(formData.doctorId), notes: formData.notes.trim() || null }; try { const created = await createAppointment(payload); setIsFormOpen(false); setFormData(emptyAppointment); setSuccessMessage(`Appointment ${created.appointmentNumber} booked successfully.`); await loadData(); } catch (requestError) { setFormError(requestError.message); } finally { setSaving(false); } };
	return <section className="module-page"><PageHeader title="Appointments" description="Schedule and track patient consultations." action={<button className="primary-button" type="button" onClick={() => setIsFormOpen(true)} disabled={!patients.length || !doctors.length}>+ Book appointment</button>} />
		{successMessage && <div className="success-banner" role="status">{successMessage}<button type="button" onClick={() => setSuccessMessage("")} aria-label="Dismiss success message">×</button></div>}
		{isFormOpen && <Modal title="Book appointment" onClose={closeForm}><form className="patient-form modal-body" onSubmit={submit}><label>Patient *<select name="patientId" value={formData.patientId} onChange={handleChange} required><option value="">Select patient</option>{patients.map((patient) => <option key={patient.patientId} value={patient.patientId}>{patient.fullName} ({patient.patientNumber})</option>)}</select></label><label>Doctor *<select name="doctorId" value={formData.doctorId} onChange={handleChange} required><option value="">Select doctor</option>{doctors.map((doctor) => <option key={doctor.doctorId} value={doctor.doctorId}>{doctor.fullName} ({doctor.doctorNumber})</option>)}</select></label><label>Date *<input name="appointmentDate" type="date" min={today} value={formData.appointmentDate} onChange={handleChange} required /></label><label>Time *<input name="appointmentTime" type="time" value={formData.appointmentTime} onChange={handleChange} required /></label><label>Reason *<input name="reason" value={formData.reason} onChange={handleChange} maxLength="255" required /></label><label>Status *<select name="status" value={formData.status} onChange={handleChange} required><option value="SCHEDULED">Scheduled</option><option value="CONFIRMED">Confirmed</option><option value="WAITING">Waiting</option><option value="COMPLETED">Completed</option><option value="CANCELLED">Cancelled</option><option value="NO_SHOW">No show</option></select></label><label className="form-field-wide">Notes<textarea name="notes" value={formData.notes} onChange={handleChange} maxLength="500" rows="3" /></label>{formError && <p className="form-error" role="alert">{formError}</p>}<div className="form-actions"><button className="secondary-button" type="button" onClick={closeForm}>Cancel</button><button className="primary-button" type="submit" disabled={saving}>{saving ? "Saving…" : "Book appointment"}</button></div></form></Modal>}
		<section className="data-card"><div className="directory-toolbar"><input aria-label="Search appointments" placeholder="Search patient, doctor, reason…" value={searchTerm} onChange={(event) => setSearchTerm(event.target.value)} /><select aria-label="Doctor" value={doctorFilter} onChange={(event) => setDoctorFilter(event.target.value)}><option>All doctors</option>{doctors.map((doctor) => <option key={doctor.doctorId} value={doctor.doctorId}>{doctor.fullName}</option>)}</select><select aria-label="Status" value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option>All status</option>{[...new Set(appointments.map((appointment) => appointment.status).filter(Boolean))].map((value) => <option key={value}>{value}</option>)}</select><button className="secondary-button" type="button" onClick={loadData} disabled={loading}>Refresh</button></div>{error ? <StatePanel title="Unable to load appointments" description={error} tone="error" action={<button className="secondary-button" type="button" onClick={loadData}>Try again</button>} /> : loading ? <StatePanel title="Loading appointments…" /> : visibleAppointments.length === 0 ? <StatePanel title="No appointments found." /> : <div className="table-scroll"><table className="directory-table"><thead><tr><th>Appointment</th><th>Patient</th><th>Doctor</th><th>Date</th><th>Time</th><th>Reason</th><th>Status</th></tr></thead><tbody>{visibleAppointments.map((appointment) => <tr key={appointment.appointmentId ?? appointment.appointmentNumber}><td data-label="Appointment"><strong>{appointment.appointmentNumber}</strong></td><td data-label="Patient">{appointment.patientName}</td><td data-label="Doctor">{appointment.doctorName}</td><td data-label="Date">{appointment.appointmentDate}</td><td data-label="Time">{appointment.appointmentTime}</td><td data-label="Reason">{appointment.reason}</td><td data-label="Status"><StatusBadge>{appointment.status}</StatusBadge></td></tr>)}</tbody></table></div>}</section>
	</section>;
}

export default Appointments;
