import { useCallback, useEffect, useMemo, useState } from "react";
import Modal from "../components/Modal";
import PageHeader from "../components/PageHeader";
import StatePanel from "../components/StatePanel";
import StatusBadge from "../components/StatusBadge";
import { getDoctors } from "../services/doctorService";
import { getOPDVisits } from "../services/opdService";
import { createIPDAdmission, dischargeIPDAdmission, getIPDAdmissions, getIPDBeds } from "../services/ipdService";
import { getPatients } from "../services/patientService";

const today = () => new Date().toISOString().slice(0, 10);
const emptyAdmission = { patientId: "", doctorId: "", opdVisitId: "", admissionDate: today(), bedId: "", admissionReason: "", diagnosis: "", treatmentPlan: "" };

function IPD() {
	const [admissions, setAdmissions] = useState([]); const [beds, setBeds] = useState([]); const [patients, setPatients] = useState([]); const [doctors, setDoctors] = useState([]); const [opdVisits, setOpdVisits] = useState([]);
	const [searchTerm, setSearchTerm] = useState(""); const [status, setStatus] = useState("All status"); const [ward, setWard] = useState("All wards"); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [formOpen, setFormOpen] = useState(false); const [formData, setFormData] = useState(emptyAdmission); const [formError, setFormError] = useState(""); const [saving, setSaving] = useState(false); const [success, setSuccess] = useState(""); const [selected, setSelected] = useState(null); const [dischargeTarget, setDischargeTarget] = useState(null); const [dischargeSummary, setDischargeSummary] = useState("");
	const loadData = useCallback(async () => { setLoading(true); setError(""); try { const [admissionData, bedData, patientData, doctorData, opdData] = await Promise.all([getIPDAdmissions(), getIPDBeds(), getPatients(), getDoctors(), getOPDVisits()]); setAdmissions(Array.isArray(admissionData) ? admissionData : []); setBeds(Array.isArray(bedData) ? bedData : []); setPatients(Array.isArray(patientData) ? patientData : []); setDoctors(Array.isArray(doctorData) ? doctorData : []); setOpdVisits(Array.isArray(opdData) ? opdData : []); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } }, []);
	useEffect(() => { const timer = window.setTimeout(loadData, 0); return () => window.clearTimeout(timer); }, [loadData]);
	const wards = [...new Set(beds.map((bed) => bed.wardName).filter(Boolean))]; const availableBeds = beds.filter((bed) => bed.status === "AVAILABLE");
	const visibleAdmissions = useMemo(() => admissions.filter((admission) => { const query = searchTerm.trim().toLowerCase(); const matches = !query || [admission.ipdNumber, admission.patientName, admission.patientNumber, admission.doctorName, admission.bedNumber].filter(Boolean).some((value) => value.toLowerCase().includes(query)); return matches && (status === "All status" || admission.status === status) && (ward === "All wards" || admission.wardName === ward); }), [admissions, searchTerm, status, ward]);
	const handleChange = ({ target: { name, value } }) => setFormData((current) => ({ ...current, [name]: value, ...(name === "patientId" || name === "doctorId" ? { opdVisitId: "" } : {}) }));
	const matchingOPD = opdVisits.filter((visit) => (!formData.patientId || String(visit.patientId) === String(formData.patientId)) && (!formData.doctorId || String(visit.doctorId) === String(formData.doctorId)));
	const closeForm = () => { if (!saving) { setFormOpen(false); setFormData({ ...emptyAdmission, admissionDate: today() }); setFormError(""); } };
	const submit = async (event) => { event.preventDefault(); setSaving(true); setFormError(""); const payload = { ...formData, patientId: Number(formData.patientId), doctorId: Number(formData.doctorId), bedId: Number(formData.bedId), opdVisitId: formData.opdVisitId ? Number(formData.opdVisitId) : null, diagnosis: formData.diagnosis.trim() || null, treatmentPlan: formData.treatmentPlan.trim() || null }; try { const created = await createIPDAdmission(payload); setFormOpen(false); setFormData(emptyAdmission); setSuccess(`${created.ipdNumber} admitted to ${created.bedNumber}.`); await loadData(); } catch (requestError) { setFormError(requestError.message); } finally { setSaving(false); } };
	const discharge = async (event) => { event.preventDefault(); try { const result = await dischargeIPDAdmission(dischargeTarget.ipdAdmissionId, dischargeSummary); setDischargeTarget(null); setDischargeSummary(""); setSuccess(`${result.ipdNumber} discharged and ${result.bedNumber} released.`); await loadData(); } catch (requestError) { setError(requestError.message); } };
	const statusTone = (value) => value === "ADMITTED" ? "warning" : value === "DISCHARGED" ? "success" : "neutral";
	return <section className="module-page"><PageHeader title="IPD" description="Track admissions, room assignments, beds, and discharges." action={<button className="primary-button" type="button" onClick={() => setFormOpen(true)} disabled={!patients.length || !doctors.length || !availableBeds.length}>+ Admit patient</button>} />
		{success && <div className="success-banner" role="status">{success}<button type="button" onClick={() => setSuccess("")} aria-label="Dismiss success message">×</button></div>}
		{formOpen && <Modal title="Register IPD admission" onClose={closeForm}><form className="patient-form modal-body" onSubmit={submit}><label>Patient *<select name="patientId" value={formData.patientId} onChange={handleChange} required><option value="">Select patient</option>{patients.map((value) => <option key={value.patientId} value={value.patientId}>{value.fullName} ({value.patientNumber})</option>)}</select></label><label>Admitting doctor *<select name="doctorId" value={formData.doctorId} onChange={handleChange} required><option value="">Select doctor</option>{doctors.map((value) => <option key={value.doctorId} value={value.doctorId}>{value.fullName} ({value.doctorNumber})</option>)}</select></label><label>OPD visit<select name="opdVisitId" value={formData.opdVisitId} onChange={handleChange}><option value="">Direct admission</option>{matchingOPD.map((value) => <option key={value.opdVisitId} value={value.opdVisitId}>{value.opdNumber} · {value.visitDate}</option>)}</select></label><label>Admission date *<input name="admissionDate" type="date" min={today()} value={formData.admissionDate} onChange={handleChange} required /></label><label>Available bed *<select name="bedId" value={formData.bedId} onChange={handleChange} required><option value="">Select bed</option>{availableBeds.map((value) => <option key={value.bedId} value={value.bedId}>{value.wardName} · {value.roomNumber} · {value.bedNumber}</option>)}</select></label><label className="form-field-wide">Admission reason *<textarea name="admissionReason" value={formData.admissionReason} onChange={handleChange} maxLength="500" rows="2" required /></label><label>Diagnosis<textarea name="diagnosis" value={formData.diagnosis} onChange={handleChange} maxLength="500" rows="2" /></label><label>Treatment plan<textarea name="treatmentPlan" value={formData.treatmentPlan} onChange={handleChange} maxLength="500" rows="2" /></label>{formError && <p className="form-error" role="alert">{formError}</p>}<div className="form-actions"><button className="secondary-button" type="button" onClick={closeForm}>Cancel</button><button className="primary-button" type="submit" disabled={saving}>{saving ? "Saving…" : "Admit patient"}</button></div></form></Modal>}
		{dischargeTarget && <Modal title={`Discharge ${dischargeTarget.ipdNumber}`} onClose={() => setDischargeTarget(null)}><form className="modal-body patient-form" onSubmit={discharge}><label className="form-field-wide">Discharge summary *<textarea value={dischargeSummary} onChange={(event) => setDischargeSummary(event.target.value)} maxLength="500" rows="4" required /></label><div className="form-actions"><button className="secondary-button" type="button" onClick={() => setDischargeTarget(null)}>Cancel</button><button className="primary-button" type="submit">Discharge patient</button></div></form></Modal>}
		<div className="summary-cards"><article className="summary-card"><div><p>Total admitted</p><h2>{admissions.filter((value) => value.status === "ADMITTED").length}</h2></div></article><article className="summary-card"><div><p>Available beds</p><h2>{availableBeds.length}</h2></div></article><article className="summary-card"><div><p>Occupied beds</p><h2>{beds.filter((value) => value.status === "OCCUPIED").length}</h2></div></article></div>
		<section className="data-card"><div className="directory-toolbar"><input aria-label="Search IPD admissions" placeholder="Search IPD, patient, doctor, bed…" value={searchTerm} onChange={(event) => setSearchTerm(event.target.value)} /><select aria-label="Ward" value={ward} onChange={(event) => setWard(event.target.value)}><option>All wards</option>{wards.map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Status" value={status} onChange={(event) => setStatus(event.target.value)}><option>All status</option><option>ADMITTED</option><option>DISCHARGED</option><option>CANCELLED</option></select><button className="secondary-button" type="button" onClick={loadData} disabled={loading}>Refresh</button></div>{error ? <StatePanel title="Unable to load IPD" description={error} tone="error" action={<button className="secondary-button" type="button" onClick={loadData}>Try again</button>} /> : loading ? <StatePanel title="Loading IPD admissions…" /> : visibleAdmissions.length === 0 ? <StatePanel title="No IPD admissions found." description="Admit a patient to begin inpatient care." /> : <div className="table-scroll"><table className="directory-table"><thead><tr><th>IPD number</th><th>Patient</th><th>Doctor</th><th>Ward / Room / Bed</th><th>Admission date</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visibleAdmissions.map((value) => <tr key={value.ipdAdmissionId}><td data-label="IPD number"><strong>{value.ipdNumber}</strong></td><td data-label="Patient">{value.patientName}<small>{value.patientNumber}</small></td><td data-label="Doctor">{value.doctorName}<small>{value.doctorNumber}</small></td><td data-label="Ward / Room / Bed">{value.wardName}<small>{value.roomNumber} · {value.bedNumber}</small></td><td data-label="Admission date">{value.admissionDate}</td><td data-label="Status"><StatusBadge tone={statusTone(value.status)}>{value.status}</StatusBadge></td><td data-label="Actions"><div className="table-actions"><button className="secondary-button" type="button" onClick={() => setSelected(value)}>Details</button>{value.status === "ADMITTED" && <button className="primary-button" type="button" onClick={() => setDischargeTarget(value)}>Discharge</button>}</div></td></tr>)}</tbody></table></div>}</section>
		<section className="data-card"><div className="section-header"><div><h2>Bed availability</h2><p>Live ward and room occupancy from the backend.</p></div></div><div className="table-scroll"><table className="directory-table"><thead><tr><th>Ward</th><th>Room</th><th>Bed</th><th>Status</th></tr></thead><tbody>{beds.map((value) => <tr key={value.bedId}><td>{value.wardName}</td><td>{value.roomNumber}</td><td>{value.bedNumber}</td><td><StatusBadge tone={value.status === "AVAILABLE" ? "success" : "warning"}>{value.status}</StatusBadge></td></tr>)}</tbody></table></div></section>
		{selected && <Modal title={`${selected.ipdNumber} details`} onClose={() => setSelected(null)}><div className="profile-grid"><div><small>Patient</small><strong>{selected.patientName} ({selected.patientNumber})</strong></div><div><small>Doctor</small><strong>{selected.doctorName} ({selected.doctorNumber})</strong></div><div><small>Ward / room / bed</small><strong>{selected.wardName} · {selected.roomNumber} · {selected.bedNumber}</strong></div><div><small>Admission</small><strong>{selected.admissionDate} {selected.admissionTime}</strong></div><div><small>Status</small><strong>{selected.status}</strong></div><div><small>Reason</small><strong>{selected.admissionReason}</strong></div><div><small>Diagnosis</small><strong>{selected.diagnosis || "—"}</strong></div><div><small>Treatment plan</small><strong>{selected.treatmentPlan || "—"}</strong></div>{selected.dischargeDate && <div><small>Discharge</small><strong>{selected.dischargeDate} {selected.dischargeTime}</strong></div>}{selected.dischargeSummary && <div><small>Discharge summary</small><strong>{selected.dischargeSummary}</strong></div>}</div></Modal>}
	</section>;
}

export default IPD;
