import { useCallback, useEffect, useMemo, useState } from "react";
import Modal from "../components/Modal";
import PageHeader from "../components/PageHeader";
import StatePanel from "../components/StatePanel";
import StatusBadge from "../components/StatusBadge";
import { createNurse, getNurses } from "../services/nurseService";

const emptyNurse = { fullName: "", department: "", mobileNumber: "", email: "", shift: "Day", status: "ACTIVE" };

function Nurses() {
	const [nurses, setNurses] = useState([]); const [searchTerm, setSearchTerm] = useState(""); const [shift, setShift] = useState("All shifts"); const [status, setStatus] = useState("All status");
	const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [isFormOpen, setIsFormOpen] = useState(false); const [formData, setFormData] = useState(emptyNurse); const [formError, setFormError] = useState(""); const [saving, setSaving] = useState(false); const [successMessage, setSuccessMessage] = useState("");
	const loadNurses = useCallback(async () => { setLoading(true); setError(""); try { const data = await getNurses(); setNurses(Array.isArray(data) ? data : []); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } }, []);
	useEffect(() => { const initialLoad = window.setTimeout(loadNurses, 0); return () => window.clearTimeout(initialLoad); }, [loadNurses]);
	const visibleNurses = useMemo(() => nurses.filter((nurse) => { const query = searchTerm.trim().toLowerCase(); const matchesSearch = !query || [nurse.nurseNumber, nurse.fullName, nurse.department, nurse.mobileNumber, nurse.email].filter(Boolean).some((value) => value.toLowerCase().includes(query)); return matchesSearch && (shift === "All shifts" || nurse.shift === shift) && (status === "All status" || nurse.status === status); }), [nurses, searchTerm, shift, status]);
	const handleChange = ({ target: { name, value } }) => setFormData((current) => ({ ...current, [name]: value }));
	const closeForm = () => { if (!saving) { setIsFormOpen(false); setFormData(emptyNurse); setFormError(""); } };
	const submit = async (event) => { event.preventDefault(); setFormError(""); setSaving(true); const payload = Object.fromEntries(Object.entries(formData).map(([key, value]) => [key, value.trim?.() ?? value])); if (!payload.email) payload.email = null; try { const created = await createNurse(payload); setIsFormOpen(false); setFormData(emptyNurse); setSuccessMessage(`Nurse ${created.nurseNumber} registered successfully.`); await loadNurses(); } catch (requestError) { setFormError(requestError.message); } finally { setSaving(false); } };
	return <section className="module-page"><PageHeader title="Nurses" description="Manage nursing staff, departments, shifts, and duty status." action={<button className="primary-button" type="button" onClick={() => setIsFormOpen(true)}>+ Add nurse</button>} />
		{successMessage && <div className="success-banner" role="status">{successMessage}<button type="button" onClick={() => setSuccessMessage("")} aria-label="Dismiss success message">×</button></div>}
		{isFormOpen && <Modal title="Add nurse" onClose={closeForm}><form className="patient-form modal-body" onSubmit={submit}><label>Full name *<input name="fullName" value={formData.fullName} onChange={handleChange} maxLength="100" required /></label><label>Department *<input name="department" value={formData.department} onChange={handleChange} maxLength="100" required /></label><label>Mobile number *<input name="mobileNumber" value={formData.mobileNumber} onChange={handleChange} inputMode="numeric" pattern="[0-9]{10,15}" required /></label><label>Email<input name="email" type="email" value={formData.email} onChange={handleChange} /></label><label>Shift *<select name="shift" value={formData.shift} onChange={handleChange} required><option>Day</option><option>Night</option><option>Rotating</option></select></label><label>Status *<select name="status" value={formData.status} onChange={handleChange} required><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></label>{formError && <p className="form-error" role="alert">{formError}</p>}<div className="form-actions"><button className="secondary-button" type="button" onClick={closeForm}>Cancel</button><button className="primary-button" type="submit" disabled={saving}>{saving ? "Saving…" : "Save nurse"}</button></div></form></Modal>}
		<section className="data-card"><div className="directory-toolbar"><input aria-label="Search nurses" placeholder="Search name, ID, department…" value={searchTerm} onChange={(event) => setSearchTerm(event.target.value)} /><select aria-label="Shift" value={shift} onChange={(event) => setShift(event.target.value)}><option>All shifts</option>{[...new Set(nurses.map((nurse) => nurse.shift).filter(Boolean))].map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Status" value={status} onChange={(event) => setStatus(event.target.value)}><option>All status</option>{[...new Set(nurses.map((nurse) => nurse.status).filter(Boolean))].map((value) => <option key={value}>{value}</option>)}</select><button className="secondary-button" type="button" onClick={loadNurses} disabled={loading}>Refresh</button></div>{error ? <StatePanel title="Unable to load nurses" description={error} tone="error" action={<button className="secondary-button" type="button" onClick={loadNurses}>Try again</button>} /> : loading ? <StatePanel title="Loading nurses…" /> : visibleNurses.length === 0 ? <StatePanel title={nurses.length === 0 ? "No nurses registered yet." : "No nurses match your filters."} /> : <div className="table-scroll"><table className="directory-table"><thead><tr><th>Nurse</th><th>Nurse ID</th><th>Department</th><th>Phone</th><th>Email</th><th>Shift</th><th>Status</th></tr></thead><tbody>{visibleNurses.map((nurse) => <tr key={nurse.nurseId ?? nurse.nurseNumber}><td data-label="Nurse"><strong>{nurse.fullName}</strong></td><td data-label="Nurse ID">{nurse.nurseNumber}</td><td data-label="Department">{nurse.department}</td><td data-label="Phone">{nurse.mobileNumber}</td><td data-label="Email">{nurse.email || "—"}</td><td data-label="Shift">{nurse.shift}</td><td data-label="Status"><StatusBadge tone={nurse.status?.toLowerCase() === "active" ? "success" : "neutral"}>{nurse.status}</StatusBadge></td></tr>)}</tbody></table></div>}</section>
	</section>;
}

export default Nurses;
