import { useCallback, useEffect, useMemo, useState } from "react";
import Modal from "../components/Modal";
import PageHeader from "../components/PageHeader";
import StatePanel from "../components/StatePanel";
import StatusBadge from "../components/StatusBadge";
import { getAppointments } from "../services/appointmentService";
import { getDoctors } from "../services/doctorService";
import { createOPDVisit, checkInOPDVisit, completeOPDVisit, getOPDVisits, startOPDConsultation } from "../services/opdService";
import { getPatients } from "../services/patientService";

const getToday = () => { const date = new Date(); const month = String(date.getMonth() + 1).padStart(2, "0"); const day = String(date.getDate()).padStart(2, "0"); return `${date.getFullYear()}-${month}-${day}`; };
const emptyVisit = { patientId: "", doctorId: "", appointmentId: "", visitDate: getToday(), symptoms: "", diagnosis: "", notes: "" };

function OPD() {
	const [visits, setVisits] = useState([]); const [patients, setPatients] = useState([]); const [doctors, setDoctors] = useState([]); const [appointments, setAppointments] = useState([]);
	const [searchTerm, setSearchTerm] = useState(""); const [visitDate, setVisitDate] = useState(getToday()); const [status, setStatus] = useState("All status");
	const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [formOpen, setFormOpen] = useState(false); const [formData, setFormData] = useState(emptyVisit); const [formError, setFormError] = useState(""); const [saving, setSaving] = useState(false); const [successMessage, setSuccessMessage] = useState(""); const [selectedVisit, setSelectedVisit] = useState(null); const [actionId, setActionId] = useState(null);

	const loadData = useCallback(async () => { setLoading(true); setError(""); try { const [visitData, patientData, doctorData, appointmentData] = await Promise.all([getOPDVisits(), getPatients(), getDoctors(), getAppointments()]); setVisits(Array.isArray(visitData) ? visitData : []); setPatients(Array.isArray(patientData) ? patientData : []); setDoctors(Array.isArray(doctorData) ? doctorData : []); setAppointments(Array.isArray(appointmentData) ? appointmentData : []); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } }, []);
	useEffect(() => { const initialLoad = window.setTimeout(loadData, 0); return () => window.clearTimeout(initialLoad); }, [loadData]);

	const visibleVisits = useMemo(() => visits.filter((visit) => { const query = searchTerm.trim().toLowerCase(); const matchesSearch = !query || [visit.opdNumber, visit.patientNumber, visit.patientName, visit.doctorNumber, visit.doctorName, visit.symptoms, visit.diagnosis].filter(Boolean).some((value) => value.toLowerCase().includes(query)); return (!visitDate || visit.visitDate === visitDate) && (status === "All status" || visit.status === status) && matchesSearch; }), [visits, visitDate, status, searchTerm]);
	const availableAppointments = appointments.filter((appointment) => (!formData.patientId || String(appointment.patientId) === String(formData.patientId)) && (!formData.doctorId || String(appointment.doctorId) === String(formData.doctorId)));
	const handleChange = ({ target: { name, value } }) => setFormData((current) => ({ ...current, [name]: value, ...(name === "patientId" || name === "doctorId" ? { appointmentId: "" } : {}) }));
	const closeForm = () => { if (!saving) { setFormOpen(false); setFormData({ ...emptyVisit, visitDate }); setFormError(""); } };
	const submit = async (event) => { event.preventDefault(); setFormError(""); setSaving(true); const payload = { ...formData, patientId: Number(formData.patientId), doctorId: Number(formData.doctorId), appointmentId: formData.appointmentId ? Number(formData.appointmentId) : null, symptoms: formData.symptoms.trim() || null, diagnosis: formData.diagnosis.trim() || null, notes: formData.notes.trim() || null }; try { const created = await createOPDVisit(payload); setFormOpen(false); setFormData({ ...emptyVisit, visitDate }); setSuccessMessage(`${created.opdNumber} registered in queue ${created.queueNumber}.`); await loadData(); } catch (requestError) { setFormError(requestError.message); } finally { setSaving(false); } };
	const runAction = async (visit, action, message) => { setActionId(visit.opdVisitId); setError(""); try { await action(visit.opdVisitId); setSuccessMessage(message); await loadData(); if (selectedVisit?.opdVisitId === visit.opdVisitId) setSelectedVisit(null); } catch (requestError) { setError(requestError.message); } finally { setActionId(null); } };
	const statusTone = (value) => value === "COMPLETED" ? "success" : value === "IN_CONSULTATION" ? "warning" : "neutral";

	return <section className="module-page"><PageHeader title="OPD" description="Manage today's outpatient queue and consultation progress." action={<button className="primary-button" type="button" onClick={() => setFormOpen(true)} disabled={!patients.length || !doctors.length}>+ Register OPD visit</button>} />
		{successMessage && <div className="success-banner" role="status">{successMessage}<button type="button" onClick={() => setSuccessMessage("")} aria-label="Dismiss success message">×</button></div>}
		{formOpen && <Modal title="Register OPD visit" onClose={closeForm}><form className="patient-form modal-body" onSubmit={submit}><label>Patient *<select name="patientId" value={formData.patientId} onChange={handleChange} required><option value="">Select patient</option>{patients.map((patient) => <option key={patient.patientId} value={patient.patientId}>{patient.fullName} ({patient.patientNumber})</option>)}</select></label><label>Doctor *<select name="doctorId" value={formData.doctorId} onChange={handleChange} required><option value="">Select doctor</option>{doctors.map((doctor) => <option key={doctor.doctorId} value={doctor.doctorId}>{doctor.fullName} ({doctor.doctorNumber})</option>)}</select></label><label>Appointment<select name="appointmentId" value={formData.appointmentId} onChange={handleChange}><option value="">Walk-in visit</option>{availableAppointments.map((appointment) => <option key={appointment.appointmentId} value={appointment.appointmentId}>{appointment.appointmentNumber} · {appointment.appointmentDate} {appointment.appointmentTime}</option>)}</select></label><label>Visit date *<input name="visitDate" type="date" min={getToday()} value={formData.visitDate} onChange={handleChange} required /></label><label className="form-field-wide">Symptoms<textarea name="symptoms" value={formData.symptoms} onChange={handleChange} maxLength="500" rows="2" /></label><label>Diagnosis<textarea name="diagnosis" value={formData.diagnosis} onChange={handleChange} maxLength="500" rows="2" /></label><label>Notes<textarea name="notes" value={formData.notes} onChange={handleChange} maxLength="500" rows="2" /></label>{formError && <p className="form-error" role="alert">{formError}</p>}<div className="form-actions"><button className="secondary-button" type="button" onClick={closeForm}>Cancel</button><button className="primary-button" type="submit" disabled={saving}>{saving ? "Saving…" : "Register visit"}</button></div></form></Modal>}
		<section className="data-card"><div className="directory-toolbar"><input aria-label="Search OPD visits" placeholder="Search OPD, patient, doctor…" value={searchTerm} onChange={(event) => setSearchTerm(event.target.value)} /><label className="toolbar-field">Date<input aria-label="OPD date" type="date" value={visitDate} onChange={(event) => setVisitDate(event.target.value)} /></label><select aria-label="Status" value={status} onChange={(event) => setStatus(event.target.value)}><option>All status</option><option>WAITING</option><option>IN_CONSULTATION</option><option>COMPLETED</option><option>CANCELLED</option></select><button className="secondary-button" type="button" onClick={loadData} disabled={loading}>Refresh</button></div>{error && <StatePanel title="Unable to load OPD" description={error} tone="error" action={<button className="secondary-button" type="button" onClick={loadData}>Try again</button>} />}{!error && (loading ? <StatePanel title="Loading today's OPD queue…" /> : visibleVisits.length === 0 ? <StatePanel title="No OPD visits found." description="Register a patient visit to start the outpatient queue." /> : <div className="table-scroll"><table className="directory-table"><thead><tr><th>Queue</th><th>OPD number</th><th>Patient</th><th>Doctor</th><th>Appointment</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visibleVisits.map((visit) => <tr key={visit.opdVisitId}><td data-label="Queue"><strong>#{visit.queueNumber}</strong></td><td data-label="OPD number">{visit.opdNumber}</td><td data-label="Patient">{visit.patientName}<small>{visit.patientNumber}</small></td><td data-label="Doctor">{visit.doctorName}<small>{visit.doctorNumber}</small></td><td data-label="Appointment">{visit.appointmentNumber || "Walk-in"}</td><td data-label="Status"><StatusBadge tone={statusTone(visit.status)}>{visit.status}</StatusBadge></td><td data-label="Actions"><div className="table-actions"><button className="secondary-button" type="button" onClick={() => setSelectedVisit(visit)}>Details</button>{visit.status === "WAITING" && <button className="primary-button" type="button" disabled={actionId === visit.opdVisitId} onClick={() => runAction(visit, checkInOPDVisit, `${visit.opdNumber} checked in.`)}>Check in</button>}{visit.status === "IN_CONSULTATION" && !visit.consultationStartTime && <button className="secondary-button" type="button" disabled={actionId === visit.opdVisitId} onClick={() => runAction(visit, startOPDConsultation, `${visit.opdNumber} consultation started.`)}>Start</button>}{visit.status === "IN_CONSULTATION" && visit.consultationStartTime && <button className="primary-button" type="button" disabled={actionId === visit.opdVisitId} onClick={() => runAction(visit, completeOPDVisit, `${visit.opdNumber} consultation completed.`)}>Complete</button>}</div></td></tr>)}</tbody></table></div>)}</section>
		{selectedVisit && <Modal title={`${selectedVisit.opdNumber} details`} onClose={() => setSelectedVisit(null)}><div className="profile-grid"><div><small>Queue</small><strong>#{selectedVisit.queueNumber}</strong></div><div><small>Status</small><strong>{selectedVisit.status}</strong></div><div><small>Patient</small><strong>{selectedVisit.patientName} ({selectedVisit.patientNumber})</strong></div><div><small>Doctor</small><strong>{selectedVisit.doctorName} ({selectedVisit.doctorNumber})</strong></div><div><small>Visit date</small><strong>{selectedVisit.visitDate}</strong></div><div><small>Appointment</small><strong>{selectedVisit.appointmentNumber || "Walk-in"}</strong></div><div><small>Symptoms</small><strong>{selectedVisit.symptoms || "—"}</strong></div><div><small>Diagnosis</small><strong>{selectedVisit.diagnosis || "—"}</strong></div><div><small>Notes</small><strong>{selectedVisit.notes || "—"}</strong></div></div></Modal>}
	</section>;
}

export default OPD;
