import { useEffect, useMemo, useState } from "react";
import PageHeader from "../components/PageHeader";
import StatePanel from "../components/StatePanel";
import settingsService from "../services/settingsService";

const sections = [
    {
        id: "hospital",
        title: "Hospital Information",
        description:
            "Manage your hospital's basic information and contact details.",
        keys: [
            "HOSPITAL_NAME",
            "HOSPITAL_REGISTRATION_NUMBER",
            "HOSPITAL_PHONE",
            "HOSPITAL_EMAIL",
            "HOSPITAL_ADDRESS",
            "HOSPITAL_WEBSITE",
        ],
    },
    {
        id: "appointments",
        title: "Appointment Settings",
        description:
            "Configure appointment and OPD consultation timings.",
        keys: [
            "APPOINTMENT_DURATION",
            "OPD_CONSULTATION_DURATION",
            "REMINDER_MINUTES",
        ],
    },
    {
        id: "system",
        title: "System Preferences",
        description:
            "Configure timezone, date format, and language preferences.",
        keys: [
            "TIME_ZONE",
            "DATE_FORMAT",
            "DEFAULT_LANGUAGE",
        ],
    },
    {
        id: "notifications",
        title: "Notification Preferences",
        description:
            "Control notifications generated by the hospital system.",
        keys: [
            "NOTIFICATION_APPOINTMENT",
            "NOTIFICATION_PATIENT",
            "NOTIFICATION_OPD",
            "NOTIFICATION_IPD",
        ],
    },
];

const labels = {
    HOSPITAL_NAME: "Hospital Name",
    HOSPITAL_REGISTRATION_NUMBER: "Registration Number",
    HOSPITAL_PHONE: "Phone Number",
    HOSPITAL_EMAIL: "Email Address",
    HOSPITAL_ADDRESS: "Address",
    HOSPITAL_WEBSITE: "Website",

    APPOINTMENT_DURATION: "Appointment Duration",
    OPD_CONSULTATION_DURATION: "OPD Consultation Duration",
    REMINDER_MINUTES: "Reminder Time",

    TIME_ZONE: "Time Zone",
    DATE_FORMAT: "Date Format",
    DEFAULT_LANGUAGE: "Default Language",

    NOTIFICATION_APPOINTMENT: "Appointment Notifications",
    NOTIFICATION_PATIENT: "Patient Notifications",
    NOTIFICATION_OPD: "OPD Notifications",
    NOTIFICATION_IPD: "IPD Notifications",
};

function Settings() {
    const [settings, setSettings] = useState([]);
    const [draftValues, setDraftValues] = useState({});
    const [loading, setLoading] = useState(true);
    const [savingKey, setSavingKey] = useState(null);
    const [error, setError] = useState("");
    const [success, setSuccess] = useState("");

    const settingsMap = useMemo(() => {
        return settings.reduce((map, setting) => {
            map[setting.settingKey] = setting;
            return map;
        }, {});
    }, [settings]);

    const loadSettings = async () => {
        try {
            setLoading(true);
            setError("");

            const data = await settingsService.getAllSettings();

            setSettings(data);

            const values = data.reduce((map, setting) => {
                map[setting.settingKey] = setting.settingValue;
                return map;
            }, {});

            setDraftValues(values);
        } catch (err) {
            setError(
                err.message || "Unable to load hospital settings."
            );
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        loadSettings();
    }, []);

    const handleValueChange = (key, value) => {
        setDraftValues((current) => ({
            ...current,
            [key]: value,
        }));

        setError("");
        setSuccess("");
    };

    const saveSetting = async (key) => {
        const setting = settingsMap[key];

        if (!setting) {
            return;
        }

        const value = draftValues[key];

        if (
            value === undefined ||
            value === null ||
            String(value).trim() === ""
        ) {
            setError(`${labels[key] || key} cannot be empty.`);
            return;
        }

        if (
            setting.settingType === "INTEGER" &&
            !/^\d+$/.test(String(value).trim())
        ) {
            setError(`${labels[key] || key} must be a valid number.`);
            return;
        }

        if (
            setting.settingType === "BOOLEAN" &&
            value !== "true" &&
            value !== "false"
        ) {
            setError(`${labels[key] || key} must be true or false.`);
            return;
        }

        try {
            setSavingKey(key);
            setError("");
            setSuccess("");

            const updated = await settingsService.updateSetting(key, {
                settingKey: key,
                settingValue: String(value),
                settingType: setting.settingType,
                description: setting.description,
            });

            setSettings((current) =>
                current.map((item) =>
                    item.settingKey === key ? updated : item
                )
            );

            setDraftValues((current) => ({
                ...current,
                [key]: updated.settingValue,
            }));

            setSuccess(
                `${labels[key] || key} updated successfully.`
            );
        } catch (err) {
            setError(
                err.message ||
                `Unable to update ${labels[key] || key}.`
            );
        } finally {
            setSavingKey(null);
        }
    };

    const renderInput = (setting) => {
        const value = draftValues[setting.settingKey] ?? "";

        if (setting.settingType === "BOOLEAN") {
            return (
                <label className="settings-toggle">
                    <input
                        type="checkbox"
                        checked={value === "true"}
                        onChange={(event) =>
                            handleValueChange(
                                setting.settingKey,
                                String(event.target.checked)
                            )
                        }
                    />
                    <span className="settings-toggle-slider" />
                    <span>
                        {value === "true" ? "Enabled" : "Disabled"}
                    </span>
                </label>
            );
        }

        return (
            <input
                className="form-input"
                type={
                    setting.settingType === "INTEGER"
                        ? "number"
                        : setting.settingKey === "HOSPITAL_EMAIL"
                            ? "email"
                            : setting.settingKey === "HOSPITAL_WEBSITE"
                                ? "url"
                                : "text"
                }
                value={value}
                onChange={(event) =>
                    handleValueChange(
                        setting.settingKey,
                        event.target.value
                    )
                }
            />
        );
    };

    if (loading) {
        return (
            <section className="module-page">
                <PageHeader
                    title="Settings"
                    description="Configure hospital administration preferences."
                />

                <StatePanel
                    type="loading"
                    title="Loading settings"
                    message="Fetching hospital configuration..."
                />
            </section>
        );
    }

    return (
        <section className="module-page">
            <PageHeader
                title="Settings"
                description="Configure hospital administration preferences."
            />

            {error && (
                <div className="integration-notice error">
                    <strong>Unable to save settings</strong>
                    <span>{error}</span>
                </div>
            )}

            {success && (
                <div className="integration-notice success">
                    <strong>Settings updated</strong>
                    <span>{success}</span>
                </div>
            )}

            <div className="settings-page">
                {sections.map((section) => (
                    <section
                        className="settings-section"
                        key={section.id}
                    >
                        <div className="settings-section-header">
                            <div>
                                <h2>{section.title}</h2>
                                <p>{section.description}</p>
                            </div>
                        </div>

                        <div className="settings-form-grid">
                            {section.keys.map((key) => {
                                const setting = settingsMap[key];

                                if (!setting) {
                                    return null;
                                }

                                return (
                                    <article
                                        className={`settings-field-card ${
                                            key === "HOSPITAL_ADDRESS"
                                                ? "settings-field-wide"
                                                : ""
                                        }`}
                                        key={key}
                                    >
                                        <div className="settings-field-content">
                                            <label>
                                                {labels[key] || key}
                                            </label>

                                            {renderInput(setting)}

                                            {setting.description && (
                                                <small>
                                                    {setting.description}
                                                </small>
                                            )}
                                        </div>

                                        <button
                                            type="button"
                                            className="secondary-button"
                                            onClick={() =>
                                                saveSetting(key)
                                            }
                                            disabled={
                                                savingKey === key
                                            }
                                        >
                                            {savingKey === key
                                                ? "Saving..."
                                                : "Save"}
                                        </button>
                                    </article>
                                );
                            })}
                        </div>
                    </section>
                ))}
            </div>
        </section>
    );
}

export default Settings;